### ISSUE TITLE
Unable to edit the config.json

### ISSUE THREAD

**Issue by modem7** [Amateur-God/Hassio-Addons#7]
# Problem/Motivation

> Unable to edit the config.json

## Steps to reproduce

"Edit the config.json to include the IP addresses of your Android devices and any other required configuration. For example:"

All I get in the configuration page is:

![image](https://github.com/user-attachments/assets/8c356ca9-9fb5-41bf-b32b-7fb6ce2a8f0c)

**Comment by Amateur-God** [comment]
Apologies I need to update the readme, this is expected behaviour, the best and only way to add devices at the moment is using the adb connect command
